[chain]
name = "mainnet"
readingUnit = 1000
start = 81878966
url = "ws://testnet-wemix-rpc-archive.chain-api.net:8598"

[log.file]
filename = "logs/static-aidrop-scanner.log"
use = true
verbosity = 5

[log.terminal]
use = true
verbosity = 5